name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

  workflow_dispatch:

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: dev
    runs-on: ubuntu-latest

    env:
      ARTIFACT_NAME: build
      ENVIRONMENT_PREFIX: dev
      PROFILE_PATH: profiles
      RESOURCE_GROUP: Analytics.DataPlatform.Group

    steps:
      - uses: actions/checkout@v2

      - name: Getting packages to deploy
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}

      - id: sql-login
        name: Adquiring SQL Access Token
        uses: ./.github/actions/azure-resource-login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-url: "https://database.windows.net"
      
      - id: deploy-report
        name: Identifying proposed changes
        uses: ./.github/actions/run-sqlpackage
        with:
          action: 'DeployReport'
          sourcepath: $PWD/${ARTIFACT_NAME}
          outputpath: $PWD/${ARTIFACT_NAME}/${ENVIRONMENT_PREFIX}
          outputfile: deployreport.xml
          profile: ${{ github.workspace }}/${{ env.PROFILE_PATH }}/${{ env.ENVIRONMENT_PREFIX }}.profile.xml
          authtoken: ${{ steps.sql-login.outputs.token }}
      
      - id: validate-deploy
        name: Validating proposed changes
        uses: ./.github/actions/validate-sqlpackage
        with:
          environment: ${{ env.ENVIRONMENT_PREFIX }}
          sqlpackage-report: $PWD/${{ env.ARTIFACT_NAME }}/${ENVIRONMENT_PREFIX}/*.xml
          outputfile: ${{ env.ENVIRONMENT_PREFIX }}.deployreport.MD
          haltonerrors: true
      
      - name: Publishing deployment report
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: ${{ env.ENVIRONMENT_PREFIX }}.deployreport.MD

      - id: mgnt-login
        name: Adquiring Azure Resource Management Access Token
        uses: ./.github/actions/azure-resource-login
        if: steps.validate-deploy.outputs.can-ignore == 'False'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-url: "https://management.core.windows.net/"
      
      - id: database-snapshot
        name: Taking a restore point on target database
        uses: ./.github/actions/synapse-snapshot
        if: steps.validate-deploy.outputs.can-ignore == 'False'
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          profile: ${{ github.workspace }}/${{ env.PROFILE_PATH }}/${{ env.ENVIRONMENT_PREFIX }}.profile.xml
          authtoken: ${{ steps.mgnt-login.outputs.token }}
          synapse-workspace: true

      - id: deploy-target
        name: Deploying changes to target
        uses: ./.github/actions/run-sqlpackage
        if: steps.validate-deploy.outputs.can-ignore == 'False'
        with:
          action: 'Publish'
          sourcepath: $PWD/${ARTIFACT_NAME}
          profile: ${{ github.workspace }}/${{ env.PROFILE_PATH }}/${{ env.ENVIRONMENT_PREFIX }}.profile.xml
          authtoken: ${{ steps.sql-login.outputs.token }}
